export {
  JintelClient,
  JintelError,
  JintelAuthError,
  JintelUnreachableError,
  JintelValidationError,
  JINTEL_API_URL,
  validateQuery,
} from "./client.js";
export type {
  JintelResult,
  GraphQLRequestResult,
  ValidationResult,
} from "./client.js";

export {
  // Enums
  EntityTypeSchema,
  SeveritySchema,
  RiskSignalTypeSchema,
  FilingTypeSchema,
  OptionTypeSchema,
  OptionsChainSortSchema,
  ExecutiveSortSchema,
  AcquisitionDirectionSchema,
  SegmentDimensionSchema,
  GdpTypeSchema,
  SP500SeriesSchema,
  // Data schemas
  MarketQuoteSchema,
  FundamentalsSchema,
  MarketDataSchema,
  RiskSignalSchema,
  RiskProfileSchema,
  SanctionsMatchSchema,
  FilingSchema,
  RegulatoryDataSchema,
  EntitySchema,
  EconomicDataPointSchema,
  SP500DataPointSchema,
  FuturesCurvePointSchema,
  OptionsChainEntrySchema,
  // Technical analysis
  MACDResultSchema,
  BollingerBandsResultSchema,
  CrossoversSchema,
  StochasticResultSchema,
  TechnicalIndicatorsSchema,
  DerivativesDataSchema,
  // Price History
  PricePointSchema,
  TickerPriceHistorySchema,
  // News & Research
  NewsArticleSchema,
  ResearchResultSchema,
  // Social Sentiment
  SocialSentimentSchema,
  // Prediction Markets
  PredictionOutcomeSchema,
  PredictionMarketSchema,
  // Hacker News
  HackerNewsCommentSchema,
  HackerNewsStorySchema,
  // Price Events
  PriceEventTypeSchema,
  PriceEventSchema,
  // Short Interest
  ShortInterestReportSchema,
  // Campaign Finance
  PACCommitteeSchema,
  // Fama-French
  FamaFrenchSeriesSchema,
  FactorDataPointSchema,
  // Financial Statements
  FinancialStatementSchema,
  FinancialStatementsSchema,
  // Institutional Holdings
  InstitutionalHoldingSchema,
  // Analyst Consensus
  AnalystConsensusSchema,
  // Ownership & Top Holders
  OwnershipBreakdownSchema,
  TopHolderSchema,
  // Key Executives
  KeyExecutiveSchema,
  // Social Media
  RedditPostSchema,
  RedditCommentSchema,
  SocialSchema,
  // SEC Form 4 / 8-K / XBRL Segments
  InsiderTradeSchema,
  EarningsPressReleaseSchema,
  SegmentRevenueSchema,
  // Alt data
  ClinicalTrialSchema,
  FdaEventTypeSchema,
  FdaEventSchema,
  LitigationCaseSchema,
  GovernmentContractSchema,
  MacroObservationSchema,
  MacroSeriesSchema,
  // Market Status
  MarketSessionSchema,
  USMarketStatusSchema,
  // Response
  GraphQLErrorSchema,
  GraphQLResponseSchema,
  ALL_ENRICHMENT_FIELDS,
} from "./types.js";

export type {
  EntityType,
  Severity,
  RiskSignalType,
  FilingType,
  OptionType,
  OptionsChainSort,
  ExecutiveSort,
  AcquisitionDirection,
  SegmentDimension,
  GdpType,
  SP500Series,
  MarketQuote,
  Fundamentals,
  MarketData,
  RiskSignal,
  RiskProfile,
  SanctionsMatch,
  Filing,
  RegulatoryData,
  Entity,
  EconomicDataPoint,
  SP500DataPoint,
  FuturesCurvePoint,
  OptionsChainEntry,
  MACDResult,
  BollingerBandsResult,
  Crossovers,
  StochasticResult,
  TechnicalIndicators,
  DerivativesData,
  PricePoint,
  TickerPriceHistory,
  NewsArticle,
  ResearchResult,
  SocialSentiment,
  PredictionOutcome,
  PredictionMarket,
  HackerNewsComment,
  HackerNewsStory,
  PriceEventType,
  PriceEvent,
  ShortInterestReport,
  PACCommittee,
  FamaFrenchSeries,
  FactorDataPoint,
  FinancialStatement,
  FinancialStatements,
  InstitutionalHolding,
  AnalystConsensus,
  OwnershipBreakdown,
  TopHolder,
  KeyExecutive,
  RedditPost,
  RedditComment,
  Social,
  InsiderTrade,
  EarningsPressRelease,
  SegmentRevenue,
  ClinicalTrial,
  FdaEvent,
  FdaEventType,
  LitigationCase,
  GovernmentContract,
  MacroSeries,
  MacroObservation,
  MarketSession,
  USMarketStatus,
  GraphQLError,
  GraphQLResponse,
  JintelClientConfig,
  RequestOptions,
  EnrichmentField,
  ArraySubGraphOptions,
  FilingsFilterOptions,
  RiskSignalFilterOptions,
  FuturesCurveFilterOptions,
  OptionsChainFilterOptions,
  NewsFilterOptions,
  ExecutivesFilterOptions,
  InsiderTradeFilterOptions,
  EarningsFilterOptions,
  SegmentRevenueFilterOptions,
  TopHoldersFilterOptions,
  FinancialStatementFilterOptions,
  SanctionsFilterOptions,
  CampaignFinanceFilterOptions,
  ClinicalTrialFilterOptions,
  FdaEventFilterOptions,
  LitigationFilterOptions,
  GovernmentContractFilterOptions,
  DiscussionsFilterOptions,
  InstitutionalHoldingsFilterOptions,
  PredictionMarketFilterOptions,
  EnrichOptions,
  AsOfOption,
  AsOfExtension,
  AsOfFieldPolicy,
} from "./types.js";

export {
  AsOfFieldPolicySchema,
  AsOfExtensionSchema,
} from "./types.js";

export {
  // Query strings
  SEARCH_ENTITIES,
  ENTITY,
  ENTITY_BY_TICKER,
  QUOTES,
  BATCH_QUOTES,
  SANCTIONS_SCREEN,
  GDP,
  INFLATION,
  INTEREST_RATES,
  SP500_MULTIPLES,
  PRICE_HISTORY,
  FAMA_FRENCH_FACTORS,
  SHORT_INTEREST,
  CAMPAIGN_FINANCE,
  INSTITUTIONAL_HOLDINGS,
  MARKET_STATUS,
  MACRO_SERIES,
  MACRO_SERIES_BATCH,
  // Dynamic builders
  buildEnrichQuery,
  buildBatchEnrichQuery,
  // Fragments
  MARKET_QUOTE_FIELDS,
  FUNDAMENTALS_FIELDS,
  RISK_FIELDS,
  REGULATORY_FIELDS,
  TECHNICALS_FIELDS,
  DERIVATIVES_FIELDS,
  NEWS_FIELDS,
  RESEARCH_FIELDS,
  SENTIMENT_FIELDS,
  PREDICTIONS_FIELDS,
  DISCUSSIONS_FIELDS,
  HISTORY_FIELDS,
  KEY_EVENTS_FIELDS,
  SHORT_INTEREST_FIELDS,
  CAMPAIGN_FINANCE_FIELDS,
  SOCIAL_FIELDS,
  FINANCIALS_FIELDS,
  EXECUTIVES_FIELDS,
  INSTITUTIONAL_HOLDINGS_FIELDS,
  ANALYST_FIELDS,
  OWNERSHIP_FIELDS,
  TOP_HOLDERS_FIELDS,
  INSIDER_TRADES_FIELDS,
  EARNINGS_PRESS_RELEASES_FIELDS,
  SEGMENTED_REVENUE_FIELDS,
  CLINICAL_TRIALS_FIELDS,
  FDA_EVENTS_FIELDS,
  LITIGATION_FIELDS,
  GOVERNMENT_CONTRACTS_FIELDS,
} from "./queries.js";
